### ISSUE TITLE
Trouble with setting up cloned pserv on cori

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/pserv#15]
I tried to setup a cloned copy of pserv on cori after setting up the stack and got the following:
```
brycek@cori12:~> source pserv/setup/setup.sh 
eups declare: I'm unable to declare Pserv as tablefile ups/Pserv.table does not exist
Unable to find an acceptable version of Pserv
```

When I went into the setup script and changed the Pserv to pserv throughout then it worked. Is there a reason we have them capitalized? But I've definitely set this up before on my own computer and not had that problem, so I'm not sure if it's something specific about cori?

**Comment by jchiang87** [comment]
I should just delete that setup.sh script since it's not being maintained and we never settled on the "right way" to set up packages on eups.  In any case, somehow we got convince that package names should be all lower case because of Mac issues regarding case insensitivity regarding filenames, so I duly changed the filenames in the ups folder, but didn't update that setup.sh script since I never use it and don't really recommend anyone else to either, though ymmv.   In any case, this is a mac vs linux issue.

**Comment by jchiang87** [comment]
I pushed the change to master.

**Comment by jbkalmbach** [comment]
Oh, okay. Well, since there is a piece of code in the monitor that needs desc.pserv I will just comment that out for now as a hack.
